apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-request-api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: food-request-ksa
      containers:
        - name: food-request-api
          image: gcr.io/aqueous-radio-307722/food-request-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
            - name: MYSQL_HOST
              value: "jdbc:mysql://0.0.0.0/foodrequest?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false"
            - name: MYSQL_USER
              value: "root"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command:
            - "/cloud_sql_proxy"
            - "instances=aqueous-radio-307722:southamerica-east1:food-request-mysql=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: time-desconhecido-sa-secret
              mountPath: /secrets/
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---