apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-request-api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: cloud-sql-vol
          secret:
            secretName: cloudsql-sa-creds
      containers:
        - name: food-request-api
          image: gcr.io/project/food-request-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
            - name: MYSQL_HOST
              value: "jdbc:mysql://0.0.0.0/foodrequest?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false"
            - name: MYSQL_USER
              value: "root"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          env:
            - name: INSTANCE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: connectionname
                  key: connectionname
          command:
            - "/cloud_sql_proxy"
            - "-instances=$(INSTANCE_CONNECTION)=tcp:0.0.0.0:3306"
            - "-credential_file=/secrets/credentials.json"
          volumeMounts:
            - name: cloud-sql-vol
              mountPath: /secrets/
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: food-rquest-api-global-ip
  labels:
    app: api
spec:
  backend:
    serviceName: api-service
    servicePort: 8080