version: '2.4'
services:
  mysql:
    image: mysql:5.7
    container_name: food-request-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "3luproec"
      MYSQL_DATABASE: "foodrequest"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 3

  food-request:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: food-request-api
    hostname: food-request-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - "mysql:mysql"
    depends_on:
      mysql:
        condition: service_healthy